services:
  crowdsec-lapi:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec-lapi
    hostname: crowdsec-lapi
    restart: unless-stopped
    environment:
      - COLLECTIONS=crowdsecurity/linux crowdsecurity/sshd crowdsecurity/iptables
      - TZ=${TZ} # Изменить в .env
    volumes:
      - crowdsec-data:/var/lib/crowdsec/data
      - crowdsec-config:/etc/crowdsec
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/kern.log:/var/log/kern.log:ro
    ports:
      - 127.0.0.1:${API_LOCAL_PORT}:8080 # Можно изменить в .env
    healthcheck:
      test: ["CMD", "cscli", "lapi", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - crowdsec-net

  crowdsec-bouncer: # Закоментировать или удалить все до следующего сервиса если не нужен баунсер
    image: ghcr.io/shgew/cs-firewall-bouncer-docker:latest
    container_name: crowdsec-bouncer
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    environment:
      - MODE=iptables
      - API_URL=http://127.0.0.1:${API_LOCAL_PORT} # Можно изменить в .env
      - API_KEY=${API_KEY_FOR_LOCAL_BOUNCER} # Изменить в .env
    volumes:
      - ./config/crowdsec-firewall-bouncer.yaml:/config/crowdsec-firewall-bouncer.yaml:ro
      - /etc/localtime:/etc/localtime:ro

  crowdsec-dashboard: # Закоментировать или удалить все до следующего сервиса если не нужен дашборд
    image: ghcr.io/theduffman85/crowdsec-web-ui:latest
    container_name: crowdsec-dashboard
    restart: unless-stopped
    ports:
      - 127.0.0.1:8083:3000
    environment:
      - CROWDSEC_URL=http://crowdsec-lapi:8080
      - CROWDSEC_USER=${CROWDSEC_USER} # Изменить в .env
      - CROWDSEC_PASSWORD=${CROWDSEC_PASSWORD} # Изменить в .env
    volumes:
      - cs-dashboard-data:/app/data
    networks:
      - crowdsec-net
    depends_on:
      - crowdsec-lapi

  crowdsec-manager: # Закоментировать или удалить все до следующего сервиса если не нужен менеджер
    image: hhftechnology/crowdsec-manager:independent
    container_name: crowdsec-manager
    restart: unless-stopped
    ports:
      - 127.0.0.1:8084:8080
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - CONFIG_DIR=/app/config
      - DATABASE_PATH=/app/data/settings.db
      - INCLUDE_CROWDSEC=true
      - ALERT_LIST_LIMIT=5000
      - CROWDSEC_CONTAINER_NAME=crowdsec-lapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cs-manager-data:/app
    networks:
      - crowdsec-net
    depends_on:
      - crowdsec-lapi

volumes:
  crowdsec-data:
  crowdsec-config:
  cs-dashboard-data: # Закоментировать или удалить если не нужен дашборд
  cs-manager-data: # Закоментировать или удалить если не нужен менеджер

networks:
  crowdsec-net:
    driver: bridge
